-- MySQL Script generated by MySQL Workbench
-- Fri Feb 23 09:53:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema devaction
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fabmed` ;

-- -----------------------------------------------------
-- Schema devaction
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fabmed` DEFAULT CHARACTER SET utf8 ;
USE `fabmed` ;

-- -----------------------------------------------------
-- Table `fabmed`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fabmed`.`cidade` ;

CREATE TABLE IF NOT EXISTS `fabmed`. `cidade` (
  `cidid` int(11) NOT NULL AUTO_INCREMENT,
  `cidnome` varchar(60) NOT NULL,
  `ciddatacadastro` datetime DEFAULT CURRENT_TIMESTAMP,
  `ciddataalteracao` datetime DEFAULT CURRENT_TIMESTAMP,
  `cidusuario` int(11) DEFAULT NULL,
  `cidestado` int(11) DEFAULT NULL,
  PRIMARY KEY (`cidid`),
  UNIQUE KEY `cidnome` (`cidnome`,`cidestado`),
  KEY `FK_USUARIO_CIDADDE` (`cidusuario`),
  KEY `FK_ESTADO_CIDADE` (`cidestado`),
  CONSTRAINT `FK_ESTADO_CIDADE` FOREIGN KEY (`cidestado`) REFERENCES `estado` (`estid`),
  CONSTRAINT `FK_USUARIO_CIDADDE` FOREIGN KEY (`cidusuario`) REFERENCES `usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
